#!/usr/bin/env node
// Deterministic task-graph tool. Reads docs/dag/dag.json, which is the single source of
// truth for task status. Regenerates docs/PROGRESS.md so the tracker can never drift.
//
//   node scripts/dag.mjs validate        cycles, dangling deps, duplicate ids
//   node scripts/dag.mjs ready           tasks whose dependencies are all done
//   node scripts/dag.mjs waves           full parallel execution schedule
//   node scripts/dag.mjs status          counts by status and phase
//   node scripts/dag.mjs set T-001 done  set a task's status
//   node scripts/dag.mjs render          rewrite docs/PROGRESS.md
//   node scripts/dag.mjs show T-001      one task with its deps and dependents

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DAG_PATH = join(ROOT, 'docs/dag/dag.json');
const PROGRESS_PATH = join(ROOT, 'docs/PROGRESS.md');
const STATUSES = ['pending', 'planning', 'implementing', 'checking', 'done', 'blocked'];

const load = () => JSON.parse(readFileSync(DAG_PATH, 'utf8'));
const save = (dag) => writeFileSync(DAG_PATH, JSON.stringify(dag, null, 2) + '\n');
const byId = (dag) => new Map(dag.tasks.map((t) => [t.id, t]));

function validate(dag) {
  const errors = [];
  const ids = new Set();
  for (const t of dag.tasks) {
    if (ids.has(t.id)) errors.push(`duplicate id ${t.id}`);
    ids.add(t.id);
    if (!STATUSES.includes(t.status)) errors.push(`${t.id}: bad status "${t.status}"`);
    if (!t.slug || !t.title) errors.push(`${t.id}: missing slug or title`);
  }
  for (const t of dag.tasks) {
    for (const d of t.deps) {
      if (!ids.has(d)) errors.push(`${t.id}: dependency ${d} does not exist`);
      if (d === t.id) errors.push(`${t.id}: depends on itself`);
    }
  }

  // Cycle detection by Kahn's algorithm; anything left over is in a cycle.
  const indegree = new Map(dag.tasks.map((t) => [t.id, t.deps.filter((d) => ids.has(d)).length]));
  const dependents = new Map(dag.tasks.map((t) => [t.id, []]));
  for (const t of dag.tasks) {
    for (const d of t.deps) if (dependents.has(d)) dependents.get(d).push(t.id);
  }
  const queue = [...indegree].filter(([, n]) => n === 0).map(([id]) => id);
  let visited = 0;
  while (queue.length) {
    const id = queue.shift();
    visited++;
    for (const dep of dependents.get(id)) {
      indegree.set(dep, indegree.get(dep) - 1);
      if (indegree.get(dep) === 0) queue.push(dep);
    }
  }
  if (visited !== dag.tasks.length) {
    const stuck = [...indegree].filter(([, n]) => n > 0).map(([id]) => id);
    errors.push(`cycle detected among: ${stuck.join(', ')}`);
  }

  return { errors, dependents };
}

function waves(dag) {
  const map = byId(dag);
  const placed = new Map();
  const out = [];
  let remaining = dag.tasks.map((t) => t.id);
  let n = 0;
  while (remaining.length) {
    const wave = remaining.filter((id) => map.get(id).deps.every((d) => placed.has(d)));
    if (!wave.length) break; // cycle; validate() reports it
    wave.forEach((id) => placed.set(id, n));
    out.push(wave);
    remaining = remaining.filter((id) => !placed.has(id));
    n++;
  }
  return out;
}

function ready(dag) {
  const map = byId(dag);
  return dag.tasks.filter(
    (t) => t.status === 'pending' && t.deps.every((d) => map.get(d)?.status === 'done'),
  );
}

function render(dag) {
  const map = byId(dag);
  const done = dag.tasks.filter((t) => t.status === 'done');
  const inFlight = dag.tasks.filter((t) => ['planning', 'implementing', 'checking'].includes(t.status));
  const blocked = dag.tasks.filter((t) => t.status === 'blocked');
  const nextUp = ready(dag);
  const pct = Math.round((done.length / dag.tasks.length) * 100);

  const icon = { done: '[x]', pending: '[ ]', blocked: '[!]', planning: '[~]', implementing: '[~]', checking: '[~]' };
  const blockedBy = (t) =>
    t.deps.filter((d) => map.get(d)?.status !== 'done').join(', ') || '-';

  const lines = [];
  lines.push('# Progress');
  lines.push('');
  lines.push('<!-- GENERATED BY scripts/dag.mjs — DO NOT EDIT BY HAND.');
  lines.push('     Change task status with: node scripts/dag.mjs set T-0xx <status> -->');
  lines.push('');
  lines.push(`**${done.length} / ${dag.tasks.length} tasks done (${pct}%)**`);
  lines.push('');
  lines.push(`Generated ${new Date().toISOString().slice(0, 10)}.`);
  lines.push('');
  lines.push('## How an agent uses this file');
  lines.push('');
  lines.push('You were given a task ID. Find it below, then open');
  lines.push('`docs/tasks/<id>-<slug>/PLAN.md` — its `reads:` frontmatter is your complete');
  lines.push('required reading. Do not search the codebase. When you finish, run');
  lines.push('`node scripts/dag.mjs set <id> <status>` — never edit this file directly.');
  lines.push('');

  if (inFlight.length) {
    lines.push('## In flight');
    lines.push('');
    for (const t of inFlight) lines.push(`- \`${t.id}\` **${t.status}** — ${t.title}`);
    lines.push('');
  }

  if (blocked.length) {
    lines.push('## Blocked');
    lines.push('');
    for (const t of blocked) lines.push(`- \`${t.id}\` ${t.title} — waiting on ${blockedBy(t)}`);
    lines.push('');
  }

  lines.push('## Ready now (dependencies satisfied, can run in parallel)');
  lines.push('');
  if (nextUp.length) {
    for (const t of nextUp) lines.push(`- \`${t.id}\` ${t.title}  \`docs/tasks/${t.id}-${t.slug}/\``);
  } else {
    lines.push('_Nothing ready — every pending task is waiting on a dependency._');
  }
  lines.push('');

  lines.push('## All tasks by phase');
  lines.push('');
  const phases = [...new Set(dag.tasks.map((t) => t.phase))].sort((a, b) => a - b);
  for (const p of phases) {
    const tasks = dag.tasks.filter((t) => t.phase === p);
    const d = tasks.filter((t) => t.status === 'done').length;
    lines.push(`### Phase ${p} — ${dag.phases[String(p)]}  (${d}/${tasks.length})`);
    lines.push('');
    lines.push('| | Task | Title | Priority | Blocked by |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const t of tasks) {
      lines.push(
        `| ${icon[t.status]} | \`${t.id}\` | ${t.title} | ${t.priority} | ${blockedBy(t)} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Parallel execution schedule');
  lines.push('');
  lines.push('Each wave can be worked concurrently; a wave starts when the one before it is done.');
  lines.push('');
  waves(dag).forEach((w, i) => lines.push(`**Wave ${i}** (${w.length}) — ${w.join(' · ')}`));
  lines.push('');

  writeFileSync(PROGRESS_PATH, lines.join('\n'));
  return PROGRESS_PATH;
}

const [cmd, ...args] = process.argv.slice(2);
const dag = load();

switch (cmd) {
  case 'validate': {
    const { errors } = validate(dag);
    if (errors.length) {
      console.error('INVALID:\n  ' + errors.join('\n  '));
      process.exit(1);
    }
    const w = waves(dag);
    console.log(`valid: ${dag.tasks.length} tasks, ${w.length} waves, widest wave ${Math.max(...w.map((x) => x.length))}`);
    break;
  }
  case 'ready': {
    const r = ready(dag);
    if (!r.length) console.log('nothing ready');
    // A task whose PLAN.md already exists needs an implementor, not a planner. Without this
    // an orchestrator picking the work up fresh cannot tell the two apart and re-plans it.
    for (const t of r) {
      const planned = existsSync(`docs/tasks/${t.id}-${t.slug}/PLAN.md`) ? '  [plan ready]' : '';
      console.log(`${t.id}  ${t.slug.padEnd(28)} ${t.title}${planned}`);
    }
    break;
  }
  case 'waves': {
    waves(dag).forEach((w, i) => console.log(`wave ${String(i).padStart(2)} (${String(w.length).padStart(2)}): ${w.join(' ')}`));
    break;
  }
  case 'status': {
    const counts = {};
    for (const t of dag.tasks) counts[t.status] = (counts[t.status] ?? 0) + 1;
    console.log(`${dag.tasks.length} tasks:`, counts);
    break;
  }
  case 'show': {
    const t = byId(dag).get(args[0]);
    if (!t) { console.error(`no task ${args[0]}`); process.exit(1); }
    const { dependents } = validate(dag);
    console.log(JSON.stringify({ ...t, unblocks: dependents.get(t.id) }, null, 2));
    break;
  }
  case 'set': {
    const [id, status] = args;
    if (!STATUSES.includes(status)) {
      console.error(`status must be one of: ${STATUSES.join(', ')}`);
      process.exit(1);
    }
    const t = byId(dag).get(id);
    if (!t) { console.error(`no task ${id}`); process.exit(1); }
    t.status = status;
    save(dag);
    render(dag);
    console.log(`${id} -> ${status}`);
    break;
  }
  case 'render': {
    const { errors } = validate(dag);
    if (errors.length) { console.error('INVALID:\n  ' + errors.join('\n  ')); process.exit(1); }
    const dir = dirname(PROGRESS_PATH);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    console.log('wrote ' + render(dag));
    break;
  }
  default:
    console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').slice(1, 12).join('\n'));
}
